[project]
name = "ai-data-engineering-end-to-end-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thales Costa", email = "thaalescosta@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-snowflake>=1.12.1",
]

[project.scripts]
ai-data-engineering-end-to-end-project = "ai_data_engineering_end_to_end_project:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
