USE ROLE ACCOUNTADMIN;

-- COMPUTE: Extra-small, auto-suspend fast so the trial credits last.
CREATE WAREHOUSE IF NOT EXISTS ZOMATO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- DATABASE + MEDALLION SCHEMAS
CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA IF NOT EXISTS ZOMATO.BRONZE; -- ICEBERH TABLES SPARK WROTE (dbt sources)
CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW; -- ONLY USED BY THE COPY FALLBACK PATH
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING; -- CLEANED/CONFORMED (dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.MARTS; -- GOLD, ICEBERG (dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOTS; -- SCD2 HISTORY (dbt)
CREATE SCHEMA IF NOT EXISTS ZOMATO.AI; --LLM-enriched tables (OpenAI Jobs)

-- A ROLE DBT/AIRFLOW WILL USE
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;

-- LET YOUR LOGIN USE THE ROLE (REPLACE WITH YOUR SNOWFLAKE USERNAME)
SET thaalescosta = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($thaalescosta);

SELECT 'Setup complete' AS status;